version: '3.7'
services:
  mysql:
    image: "mysql/mysql-server:5.7"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "beego"
    networks:
      - net
    volumes:
      - mysql-data:/var/lib/mysql
      - ./.github/beego.sql:/sql/beego.sql
    restart: "always"
  beego-blog:
    image: "beego-blog:latest"
    build:
      context: "."
    ports:
      - "8080:8080"
    depends_on:
        - mysql
    environment:
      TEST_BEEGO_ENV: "beego"
      APP_RUNMODE: "docker"
    networks:
      - net
    restart: "always"
    deploy:
      replicas: 1

networks:
  net:
volumes:
  mysql-data: